{
    "swagger": "2.0",
    "info": {
        "title": "MiW Results REST api",
        "description": "[UPM] MiW Results REST api operations",
        "license": {
            "name": "MIT",
            "url": "http://localhost:8000/api-docs/LICENSE.txt"
        },
        "version": "0.1.0"
    },
    "host": "localhost:8000",
    "basePath": "/api/v1",
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json",
        "application/x-www-form-urlencoded"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "login"
                ],
                "summary": "Returns Results api token",
                "description": "Returns Results api token.",
                "operationId": "miw_post_login",
                "parameters": [
                    {
                        "name": "username",
                        "in": "formData",
                        "description": "User name",
                        "allowEmptyValue": false,
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "password",
                        "in": "formData",
                        "description": "User password",
                        "allowEmptyValue": false,
                        "required": true,
                        "type": "string",
                        "format": "password"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Results api token",
                        "schema": {
                            "type": "object",
                            "example": {
                                "X-Token": "<JSON web token>"
                            }
                        },
                        "headers": {
                            "X-Token": {
                                "description": "api token",
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                }
            }
        },
        "/results": {
            "get": {
                "tags": [
                    "Results"
                ],
                "summary": "Returns all results for current user",
                "description": "Returns all results from the system from the system that the user has access to.",
                "operationId": "miw_cget_results",
                "responses": {
                    "200": {
                        "description": "Results array response",
                        "schema": {
                            "$ref": "#/definitions/ResultsArray"
                        },
                        "headers": {
                            "X-Token": {
                                "description": "api token",
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Results"
                ],
                "summary": "Creates a new result",
                "description": "Creates a new result.",
                "operationId": "miw_post_results",
                "parameters": [
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`Result` properties to add to the system",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResultData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "`Created` Result created",
                        "schema": {
                            "$ref": "#/definitions/Result"
                        },
                        "headers": {
                            "X-Token": {
                                "description": "api token",
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "422": {
                        "description": "`Unprocessable entity` result is left out",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "options": {
                "tags": [
                    "Results"
                ],
                "summary": "Provides the list of HTTP supported methods",
                "description": "Return a `Allow` header with a list of HTTP supported methods.",
                "operationId": "miw_options_results",
                "responses": {
                    "200": {
                        "description": "`Allow` header <Response body is empty>"
                    }
                }
            }
        },
        "/results/{resultId}": {
            "get": {
                "tags": [
                    "Results"
                ],
                "summary": "Returns a result based on a single ID",
                "description": "Returns the result identified by `resultId`.",
                "operationId": "miw_get_results",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Result",
                        "schema": {
                            "$ref": "#/definitions/Result"
                        },
                        "headers": {
                            "X-Token": {
                                "description": "api token",
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Results"
                ],
                "summary": "Updates a result",
                "description": "Updates the result identified by `resultId`.",
                "operationId": "miw_put_results",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    },
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`Result` data to update",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResultData"
                        }
                    }
                ],
                "responses": {
                    "209": {
                        "description": "`Ok` Result previously existed and is now updated",
                        "schema": {
                            "$ref": "#/definitions/Result"
                        },
                        "headers": {
                            "X-Token": {
                                "description": "api token",
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Results"
                ],
                "summary": "Deletes a result",
                "description": "Deletes the result identified by `resultId`.",
                "operationId": "miw_delete_results",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Result deleted <Response body is empty>",
                        "headers": {
                            "X-Token": {
                                "description": "api token",
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "options": {
                "tags": [
                    "Results"
                ],
                "summary": "Provides the list of HTTP supported methods",
                "description": "Return a `Allow` header with a list of HTTP supported methods.",
                "operationId": "miw_options_results_id",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "`Allow` header <Response body is empty>"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns all users",
                "description": "Returns all users from the system that the user has access to.",
                "operationId": "miw_cget_users",
                "responses": {
                    "200": {
                        "description": "User array response",
                        "schema": {
                            "$ref": "#/definitions/UsersArray"
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "403": {
                        "$ref": "#/responses/403_Forbidden_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Creates a new user",
                "description": "Creates a new user",
                "operationId": "miw_post_users",
                "parameters": [
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`User` properties to add to the system",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "`Created` User created",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "`Bad Request` Username or email already exists.",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "403": {
                        "$ref": "#/responses/403_Forbidden_Response"
                    },
                    "422": {
                        "description": "`Unprocessable entity` Username, e-mail or password is left out",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "options": {
                "tags": [
                    "Users"
                ],
                "summary": "Provides the list of HTTP supported methods",
                "description": "Return a `Allow` header with a list of HTTP supported methods.",
                "operationId": "miw_options_users",
                "responses": {
                    "200": {
                        "description": "`Allow` header <Response body is empty>"
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns a user based on a single ID",
                "description": "Returns the user identified by `userId`.",
                "operationId": "miw_get_users",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "403": {
                        "$ref": "#/responses/403_Forbidden_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Users"
                ],
                "summary": "Updates a user",
                "description": "Updates the user identified by `userId`.",
                "operationId": "miw_put_users",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    },
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`User` data to update",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserData"
                        }
                    }
                ],
                "responses": {
                    "209": {
                        "description": "`Content Returned` User previously existed and is now updated",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "`Bad Request` User name or e-mail already exists",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "403": {
                        "$ref": "#/responses/403_Forbidden_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Users"
                ],
                "summary": "Deletes a user",
                "description": "Deletes the user identified by `userId`.",
                "operationId": "miw_delete_users",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User deleted <Response body is empty>"
                    },
                    "401": {
                        "$ref": "#/responses/401_Standard_Response"
                    },
                    "403": {
                        "$ref": "#/responses/403_Forbidden_Response"
                    },
                    "404": {
                        "$ref": "#/responses/404_Resource_Not_Found_Response"
                    }
                },
                "security": [
                    {
                        "ResultsSecurity": []
                    }
                ]
            },
            "options": {
                "tags": [
                    "Users"
                ],
                "summary": "Provides the list of HTTP supported methods",
                "description": "Return a `Allow` header with a list of HTTP supported methods.",
                "operationId": "miw_options_users_id",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "`Allow` header <Response body is empty>"
                    }
                }
            }
        }
    },
    "definitions": {
        "Result": {
            "required": [
                "id",
                "result"
            ],
            "properties": {
                "id": {
                    "description": "User Id",
                    "type": "integer",
                    "format": "int32"
                },
                "result": {
                    "description": "Result value",
                    "type": "integer",
                    "format": "int32"
                },
                "user": {
                    "description": "User",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/User"
                    }
                },
                "time": {
                    "description": "Result datetime",
                    "type": "string",
                    "format": "date-time"
                }
            },
            "example": {
                "id": 1492,
                "result": 1,
                "user": "<User data>",
                "time": "<Time data>"
            }
        },
        "ResultData": {
            "properties": {
                "result": {
                    "description": "Result value",
                    "type": "integer",
                    "format": "int64",
                    "default": 1
                }
            },
            "example": {
                "result": 84
            }
        },
        "ResultsArray": {
            "properties": {
                "results": {
                    "description": "Results array",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Result"
                    }
                }
            }
        },
        "User": {
            "required": [
                "id",
                "username",
                "email"
            ],
            "properties": {
                "id": {
                    "description": "User Id",
                    "type": "integer",
                    "format": "int32"
                },
                "username": {
                    "description": "User name",
                    "type": "string"
                },
                "email": {
                    "description": "User email",
                    "type": "string"
                },
                "enabled": {
                    "description": "Denotes if user is enabled",
                    "type": "boolean"
                },
                "isAdmin": {
                    "description": "Denotes if user has admin privileges",
                    "type": "boolean"
                }
            },
            "example": {
                "user": {
                    "id": 1508,
                    "username": "User name",
                    "email": "User email",
                    "enabled": true,
                    "admin": false
                }
            }
        },
        "UserData": {
            "properties": {
                "username": {
                    "description": "User name",
                    "type": "string"
                },
                "email": {
                    "description": "User email",
                    "type": "string"
                },
                "password": {
                    "description": "User password",
                    "type": "string",
                    "format": "password"
                },
                "enabled": {
                    "description": "Denotes if user is enabled",
                    "type": "boolean"
                },
                "isAdmin": {
                    "description": "Denotes if user has admin privileges",
                    "type": "boolean"
                }
            },
            "example": {
                "username": "User_name",
                "email": "User_email@example.com",
                "password": "User_password",
                "enabled": true,
                "isAdmin": false
            }
        },
        "UsersArray": {
            "properties": {
                "users": {
                    "description": "Users array",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/User"
                    }
                }
            }
        },
        "Message": {
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "description": "Response code",
                    "type": "integer",
                    "format": "int32"
                },
                "message": {
                    "description": "Response message",
                    "type": "string"
                }
            },
            "example": {
                "code": "HTTP code",
                "message": "Response Message"
            }
        }
    },
    "parameters": {
        "resultId": {
            "name": "resultId",
            "in": "path",
            "description": "ID of result to fetch",
            "required": true,
            "type": "integer",
            "format": "int32",
            "pattern": "[0-9]+"
        },
        "userId": {
            "name": "userId",
            "in": "path",
            "description": "ID of user",
            "required": true,
            "type": "integer",
            "format": "int32"
        }
    },
    "responses": {
        "401_Standard_Response": {
            "description": "`Unauthorized` invalid `X-Token` header",
            "schema": {
                "$ref": "#/definitions/Message"
            }
        },
        "403_Forbidden_Response": {
            "description": "`Forbidden` You don't have permission to access",
            "schema": {
                "$ref": "#/definitions/Message"
            }
        },
        "404_Resource_Not_Found_Response": {
            "description": "`Not found` resource not found",
            "schema": {
                "$ref": "#/definitions/Message"
            }
        }
    },
    "securityDefinitions": {
        "ResultsSecurity": {
            "type": "apiKey",
            "name": "X-Token",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "login",
            "description": "user login"
        },
        {
            "name": "Results",
            "description": "Results management"
        },
        {
            "name": "Users",
            "description": "Users management"
        }
    ]
}